# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper.rb"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

require 'rubygems'
require 'bundler'

require 'easy-deployment'

require 'capistrano-spec'

RSpec.configure do |config|
  config.mock_with :rspec

  config.include Capistrano::Spec::Matchers
  config.include Capistrano::Spec::Helpers
end
